name: Send Tweet
on: [push]
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: dart-actions/tweet@v1.0.1
        with:
          text: ${{ github.event.head_commit.message}} \n ${{" https://github.com/unobatbayar/problem-solving/commit/"}} + ${{ github.event.head_commit.id}}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
